#:schema https://www.schemastore.org/tombi.json

toml-version = "v1.0.0"

[format.rules]
indent-style = "space"
indent-sub-tables = false
indent-table-key-value-pairs = false
indent-width = 2
key-value-equals-sign-alignment = false
line-ending = "lf"
