import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    developer: [
        {
            className: "sb-cat-developer",
            id: "index",
            label: "🛠️ Dev",
            type: "doc",
        },
        {
            className: "sb-cat-developer-ops",
            id: "architecture",
            label: "🏗️ Docs architecture",
            type: "doc",
        },
        {
            className: "sb-cat-api-overview",
            collapsed: true,
            collapsible: true,
            description:
                "Entry point for generated API docs and the public plugin surface.",
            items: [
                {
                    className: "sb-api-overview-item",
                    id: "api/README",
                    label: "🧩 API index",
                    type: "doc",
                },
                {
                    className: "sb-api-overview-item",
                    id: "api/plugin/README",
                    label: "📦 Plugin module",
                    type: "doc",
                },
                {
                    className: "sb-api-overview-item",
                    id: "api/plugin/type-aliases/CopilotPluginContract",
                    label: "🧠 Type alias · CopilotPluginContract",
                    type: "doc",
                },
                {
                    className: "sb-api-overview-item",
                    id: "api/plugin/variables/plugin",
                    label: "⚙️ Runtime export · plugin",
                    type: "doc",
                },
            ],
            label: "📘 API overview",
            link: {
                id: "api/README",
                type: "doc",
            },
            type: "category",
        },
        {
            className: "sb-cat-developer-adr",
            collapsed: true,
            collapsible: true,
            description:
                "Architectural decisions behind the docs split, generated matrices, and large catalog navigation.",
            items: [
                {
                    className: "sb-adr-item",
                    id: "adrs/index",
                    label: "📚 ADR index",
                    type: "doc",
                },
                {
                    className: "sb-adr-item",
                    id: "adrs/split-product-pages-from-rule-docs",
                    label: "ADR 0001 · Split product pages",
                    type: "doc",
                },
                {
                    className: "sb-adr-item",
                    id: "adrs/shared-generated-rule-matrix",
                    label: "ADR 0002 · Shared rule matrix",
                    type: "doc",
                },
                {
                    className: "sb-adr-item",
                    id: "adrs/navigable-large-rule-catalogs",
                    label: "ADR 0003 · Navigable rule catalogs",
                    type: "doc",
                },
            ],
            label: "🧭 Architecture decisions",
            link: {
                id: "adrs/index",
                type: "doc",
            },
            type: "category",
        },
        {
            className: "sb-cat-dev-charts",
            collapsed: true,
            collapsible: true,
            description:
                "Workflow maps for docs publishing, sync surfaces, and validation.",
            items: [
                {
                    id: "workflow-charts",
                    label: "📊 Docs & API pipeline",
                    type: "doc",
                },
            ],
            label: "📊 Charts",
            link: {
                description:
                    "Workflow maps for docs publishing, sync surfaces, and validation.",
                slug: "/charts",
                title: "Workflow charts",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-api-types",
            collapsed: true,
            collapsible: true,
            description:
                "Type-level contracts and preset/rule aliases exposed from the public plugin module.",
            items: [
                {
                    dirName: "api/plugin/type-aliases",
                    type: "autogenerated",
                },
            ],
            label: "🧠 Types",
            link: {
                description:
                    "Type-level contracts and preset/rule aliases exposed from the public plugin module.",
                slug: "/api/types",
                title: "Plugin type aliases",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-api-runtime",
            collapsed: true,
            collapsible: true,
            description:
                "Runtime exports plus the internal utilities that power the plugin and docs sync flows.",
            items: [
                {
                    className: "sb-subcat-api-runtime-plugin",
                    collapsed: true,
                    collapsible: true,
                    items: [
                        {
                            dirName: "api/plugin/variables",
                            type: "autogenerated",
                        },
                    ],
                    label: "Plugin variables",
                    type: "category",
                },
                {
                    className: "sb-subcat-api-runtime-internal",
                    collapsed: true,
                    collapsible: true,
                    items: [
                        {
                            dirName: "api/internal",
                            type: "autogenerated",
                        },
                    ],
                    label: "Internal API",
                    type: "category",
                },
            ],
            label: "⚙️ Runtime",
            link: {
                description:
                    "Runtime exports and the internal utility inventory behind eslint-plugin-copilot.",
                slug: "/api/runtime",
                title: "Runtime exports",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-dev-links",
            collapsed: true,
            collapsible: true,
            description:
                "Quick links to the repo, package, public pages, and maintainer-facing surfaces.",
            items: [
                {
                    href: "/project",
                    label: "📈 Project page",
                    type: "link",
                },
                {
                    href: "/resources",
                    label: "📚 Resources",
                    type: "link",
                },
                {
                    href: "/docs/rules/overview",
                    label: "📋 Rule overview",
                    type: "link",
                },
                {
                    href: "https://github.com/Nick2bad4u/eslint-plugin-copilot",
                    label: "🐙 GitHub",
                    type: "link",
                },
                {
                    href: "https://www.npmjs.com/package/eslint-plugin-copilot",
                    label: "📦 npm package",
                    type: "link",
                },
            ],
            label: "🌐 Links",
            link: {
                description:
                    "Quick links to the repo, package, public pages, and maintainer-facing surfaces.",
                slug: "/links",
                title: "Developer links",
                type: "generated-index",
            },
            type: "category",
        },
    ],
};

export default sidebars;
