import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

type SidebarDocConfig = Readonly<{
    className?: string;
    id: string;
    label: string;
    type: "doc";
}>;

type SidebarCategoryConfig = Readonly<{
    className?: string;
    collapsed: boolean;
    collapsible: boolean;
    items: readonly SidebarConfigItem[];
    label: string;
    type: "category";
}>;

type SidebarAutogeneratedConfig = Readonly<{
    className?: string;
    dirName: string;
    type: "autogenerated";
}>;

type SidebarConfigItem =
    | SidebarAutogeneratedConfig
    | SidebarCategoryConfig
    | SidebarDocConfig;

const doc = (
    id: string,
    label: string,
    className: string
): SidebarDocConfig => ({
    className,
    id,
    label,
    type: "doc",
});

const category = (
    label: string,
    className: string,
    items: readonly SidebarConfigItem[]
): SidebarCategoryConfig => ({
    className,
    collapsed: false,
    collapsible: true,
    items,
    label,
    type: "category",
});

const sidebars = {
    developer: [
        doc("index", "🛠️ Overview", "sidebar-doc sidebar-doc--overview"),
        doc(
            "architecture",
            "🏗️ Architecture",
            "sidebar-doc sidebar-doc--guide"
        ),
        doc(
            "workflow-charts",
            "🗺️ Workflow charts",
            "sidebar-doc sidebar-doc--guide"
        ),
        category(
            "📐 ADRs",
            "sidebar-category sidebar-category--developer-adrs",
            [
                doc("adrs/index", "Overview", "sidebar-doc sidebar-doc--guide"),
                doc(
                    "adrs/split-product-pages-from-rule-docs",
                    "ADR 0001 · Split product pages from rule docs",
                    "sidebar-doc sidebar-doc--developer-adr"
                ),
                doc(
                    "adrs/shared-generated-rule-matrix",
                    "ADR 0002 · Shared generated rule matrix",
                    "sidebar-doc sidebar-doc--developer-adr"
                ),
                doc(
                    "adrs/navigable-large-rule-catalogs",
                    "ADR 0003 · Navigable large rule catalogs",
                    "sidebar-doc sidebar-doc--developer-adr"
                ),
            ]
        ),
        category(
            "📚 API reference",
            "sidebar-category sidebar-category--developer-api",
            [{ dirName: "api", type: "autogenerated" }]
        ),
    ],
} as unknown as SidebarsConfig;

export default sidebars;
